# Работа с матрицами/массивами в Python (библиотека [`numpy`](https://numpy.org/))

In [1]:
import numpy as np

## Матрицы в `numpy`

<div style="background-color:Bisque; color:DarkBlue; padding:30px;">

- Для задания матриц используем метод `numpy.array()` 
- Матрицы задаются __построчно__ (как список строк)
- Размер матрицы находится в `.shape` 

</div>

__Пример__: Зададим матрицу

$$
	A=\begin{pmatrix} 1 & 2 & 0 \\ -1 & 0 & 1 \\ 1 & 0 & 1 \end{pmatrix}
$$

In [2]:
A = np.array([[1, 2, 0], [-1, 0, 1], [1, 0, 1]])
print(A)

[[ 1  2  0]
 [-1  0  1]
 [ 1  0  1]]


In [3]:
# её размер
print(A.shape)

(3, 3)


## Скалярное умножение матриц


<div style="background-color:Bisque; color:DarkBlue; padding:30px;">

Пусть $A_{n,m}=(a_{ij})$ и $c\in\mathbb{R}$. Тогда

$$
	cA=(cA)_{n,m}=(ca_{ij})
$$

</div>

__Пример__: вычислим $cA$ для

$$
\begin{aligned}
	c&=3 & A&=\begin{pmatrix} 2 & 1 \\ -1 & 3\end{pmatrix}
\end{aligned}
$$

In [4]:
A = np.array([[2, 1], [-1, 3]])
print(3*A)

[[ 6  3]
 [-3  9]]


## Сложение/вычитание матриц

<div style="background-color:Bisque; color:DarkBlue; padding:30px;">

Для произвольных матриц __одного и того же размера__ $A_{n,m}=(a_{ij}), B_{n,m}=(b_{ij})$ можно определить

$$
	A\pm B =(A\pm B)_{n,m}=(a_{ij}\pm b_{ij})
$$

</div>



__Пример__: Вычислим 

$$
\begin{aligned}
	A&\pm B & A&=\begin{pmatrix} 0 & 1 & 1 \\ 2 & -1 & 0\end{pmatrix} & B&=\begin{pmatrix} 1 & 2 & -2 \\ 0 & 1 & -2\end{pmatrix}
\end{aligned}
$$

In [5]:
A = np.array([[0, 1, 1], [2, -1, 0]])
B = np.array([[1, 2, -2], [0, 1, -2]])
print(A+B)
print(A-B)

[[ 1  3 -1]
 [ 2  0 -2]]
[[-1 -1  3]
 [ 2 -2  2]]


## Транспонирование матриц

<div style="background-color:Bisque; color:DarkBlue; padding:30px;">

Для произвольной матрицы $A_{n,m}=(a_{ij})$ определим __транспонированную марицу__ $A^\top_{m,n}$ как

$$
	[A^\top]_{i,j}=[A]_{j,i}
$$

</div>

__Пример__: Вычислим 

$$
\begin{aligned}
	&A^\top & A&=\begin{pmatrix} 1 & 1 \\ 0 & -1 \\ 2 & 1 \\ 1 & -1 \end{pmatrix}
\end{aligned}
$$

In [6]:
A = np.array([[1, 1], [0, -1], [2, 1], [1, -1]])
print(A.T)

[[ 1  0  2  1]
 [ 1 -1  1 -1]]


## Умножение матриц

### произведение Адамара

<div style="background-color:Bisque; color:DarkBlue; padding:30px;">

Для произвольных матриц __одного и того же размера__ $A_{n,m}=(a_{ij}), B_{n,m}=(b_{ij})$ можно определить __их произведение Адамара__ (умножение поэлементно!)

$$
	A\odot B =(A\odot B)_{n,m}=(a_{ij}\cdot b_{ij})
$$

Очевидно

$$
	A\odot B=B\odot A
$$

</div>

__Пример__: Вычислим 

$$
\begin{aligned}
	A&\odot B & A&=\begin{pmatrix} 0 & 1 & 1 \\ 2 & -1 & 0\end{pmatrix} & B&=\begin{pmatrix} 1 & 2 & -2 \\ 0 & 1 & -2\end{pmatrix}
\end{aligned}
$$

In [7]:
A = np.array([[0, 1, 1], [2, -1, 0]])
B = np.array([[1, 2, -2], [0, 1, -2]])
print(A*B)

[[ 0  2 -2]
 [ 0 -1  0]]


### Матричное произведение

<div style="background-color:Bisque; color:DarkBlue; padding:30px;">

Для произвольных матриц $A_{n,k}=(a_{ij}), B_{k,m}=(b_{ij})$ можно определить их __произведение (важен порядок!)__

$$
\begin{aligned}
	AB&=(AB)_{n,m} & [AB]_{i,j}&=\sum_{l=1}^k[A]_{i,l}[B]_{l,j}
\end{aligned}
$$

**<span style="color:purple">Замечание :</span>**
- Число столбцов в первом множителе д.б. равно числу строк во втором множителе. __Иначе произведение не определено__
- В произведении элементы строка $i$ матрицы $A$ умножаются и складывается с элементами столбца $j$ матрицы $B$
- Порядок множителе важен. В общем случае $AB\ne BA$
- Для вычисления матричного произведения в `numpy` используется символ `@`

</div>

__Пример__: Вычислим 

$$
\begin{aligned}
	A&B & A&=\begin{pmatrix} 0 & 1 & 1 \\ 2 & -1 & 0\end{pmatrix} & B&=\begin{pmatrix} 1 & 2 \\ -2 & 0 \\ 1 & -1\end{pmatrix}
\end{aligned}
$$

Вначале убедимся, что произведение определено

In [8]:
A = np.array([[0, 1, 1], [2, -1, 0]])
B = np.array([[1, 2] , [-2, 0], [1, -1]])
A.shape, B.shape

((2, 3), (3, 2))

In [9]:
# проверим, что произведение определено
if A.shape[1] == B.shape[0]:
	print(f'Произведение AB определено. Произведение AB имеет размер {A.shape[0], B.shape[1]}')
else:
	print(f'Произведение AB не определено')

Произведение AB определено. Произведение AB имеет размер (2, 2)


In [10]:
print(A@B)

[[-1 -1]
 [ 4  4]]


## Обратная матрица

<div style="background-color:Bisque; color:DarkBlue; padding:30px;">

Пусть $A$ - квадратная матрица. Матрица $B$ называется **обратной к $A$** если верны равенства

$$
	AB=BA=I
$$

где $I$ - единичная матрица соответствущего порядка.

__Обозначение__: $B=A^{-1}$

**<span style="color:purple">Замечание :</span>**
- Обратная матрица определена однозначно
- __Не любая матрица имеет обратную__
- Если матрица имеет обратную, то она __обратима__
- Для вычисления обратной матрицы используем метод `numpy.linalg.inv()`

</div>

__Пример__: Вычислим матрицу, обратную к $A=\begin{pmatrix} 5 & 3 \\ 2 & 1\end{pmatrix}$

In [11]:
A = np.array([[5, 2], [3, 1]])
np.linalg.inv(A)

array([[-1.,  2.],
       [ 3., -5.]])

## Матричные уравнения

<div style="background-color:Bisque; color:DarkBlue; padding:30px;">

Для заданных матриц $A_{n,n}$ и $B_{n,m}$ рассмотрим матричное уравнение

$$
	AX=B
$$

относительно неизвестной матрицы $X_{n,m}$

**<span style="color:purple">Предложение :</span>** если $A$ обратима, то уравнение имеет единственное решение $X=A^{-1}B$

**<span style="color:purple">Замечание 1:</span>**  Для решения уравнения 
- используем метод `numpy.linalg.solve(a,b)`
- альтернативно можно через явную формулу, предварительно вычислив обратную матрицу

**<span style="color:purple">Замечание 2:</span>** При заданных $A_{m,m},B_{n,m}$ рассмотрим уравнение $XA=B$ относительно неизвестной матрицы $X_{n,m}$. Оно сводится к предыдущем случаю транспонированием

$$
	XA=B\iff A^\top X^\top=B^\top
$$

Если матрица $A$ обратима, то это уравнение имеет единственное решения $X=BA^{-1}$

</div>

__Пример__: Решим уравнение $AX=B$ при 

$$
\begin{aligned}
	A&=\begin{pmatrix} 5 & 2 \\ 3 & 1\end{pmatrix} & B&=\begin{pmatrix} 2 & 0 & 1 \\ -1 & 1 & 2\end{pmatrix}
\end{aligned}
$$

In [12]:
A = np.array([[5, 2], [3, 1]])
B = np.array([[2, 0, 1], [-1, 1, 2]])
np.linalg.solve(A,B)

array([[-4.,  2.,  3.],
       [11., -5., -7.]])

## Определитель матрицы

<div style="background-color:Bisque; color:DarkBlue; padding:30px;">

Пусть $A$ - квадратная матрица. Для вычисления её определителя используем метод `numpy.linalg.det()`

__Обозначение__: $B=A^{-1}$

**<span style="color:purple">Свойство :</span>** Матрица $A$ обратима $\iff\det(A)\ne 0$

</div>

__Пример__: Вычисли определитель матрицы $A=\begin{pmatrix} 5 & 2 \\ 3 & 1\end{pmatrix}$

In [13]:
A = np.array([[5, 2], [3, 1]])
np.linalg.det(A)

np.float64(-1.0000000000000009)